spring.application.name=auth-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=edug
spring.datasource.password=edug123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false